### ISSUE TITLE
Intermixing Mongo API and DocumentDB API breaks document structure

### ISSUE THREAD

**Issue by jdk514** [Azure/azure-cosmos-python#111]
Working with Cosmos I initially loaded documents through the Mongo API. When shifting over to using pydocumentdb I've run into formatting issues with the generated results ($t and $v key-values are inserted throughout the document).

An example of this problem can be found on [stackoverflow](https://stackoverflow.com/questions/45815507/azure-cosmos-db-mongodb-t-and-v), but no solution is provided for switching the API used to access the data.

Expected Format:
![as72v](https://user-images.githubusercontent.com/3916001/33032330-d3898626-cdee-11e7-862e-6afc9c064622.png)

Actual Format:
![8b9pl](https://user-images.githubusercontent.com/3916001/33032329-d37db2e2-cdee-11e7-8168-e538d6143e54.png)

**Comment by moderakh** [comment]
@jdk514 there is nothing wrong here. DocumentDB API provides different view over your data. Basically you can think about it as data which gets in using MongoDB API will have a slightly different representation when looking at it through DocumetnDB API.

**Comment by alekseys** [comment]
Actually the problem described on StackOverflow looks similar but it's a different problem - they have two different schemas in different accounts. 
In your case - inter-operability of the APIs is only possible between SQL and Gremlin API, others are not inter-operable.

**Comment by jdk514** [comment]
Does this mean that if I try to connect spark to my cosmos collection it will fail? I'm following the information [here](https://github.com/Azure/azure-cosmosdb-spark/wiki/Azure-Cosmos-DB-Spark-Connector-User-Guide), which indicates I will be hooking into cosmos using the DocumnetDB Java SDK. Given the issue of intermixing API's, it looks like this process will fail as the data will be improperly formatted.

**Comment by moderakh** [comment]
@emilylawton can you please respond to the last question.

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
