### ISSUE TITLE
Wondering if the Get Uri helper methods can be moved to pydocumentdb from crud_tests.py

### ISSUE THREAD

**Issue by HussainMir** [Azure/azure-cosmos-python#112]
Hi,

I see some very good helper methods in crud_tests.py to get the Uris out of the names of the things I provide. e.g. 
def GetDocumentLink(self, database, document_collection, document, 
is_name_based=True):
        if is_name_based:
            return self.GetDocumentCollectionLink(database, document_collection) + '/docs/' + document['id']
        else:
            return document['_self']

Something like we have in .NET SDK. Are we planning for this?

**Comment by moderakh** [comment]
@HussainMir it is worth to have a UriFactory method as you mentioned in the python sdk.

For example please look at what we have in node:
https://github.com/Azure/azure-documentdb-node/blob/3aaf6f96c652bfa3e597050c8a0cd54f68844209/source/lib/uriFactory.js

If you are interested to send a PR for this we will merge your PR Hussain.

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
