### ISSUE TITLE
Proxy settings not taken into account ?

### ISSUE THREAD

**Issue by sigma87** [Azure/azure-cosmos-python#120]
Reading the documentation it should be possible to specify a proxy to use to connect to an Azure Cosmos DB :

http://azure.github.io/azure-documentdb-python/api/pydocumentdb.documents.html#pydocumentdb.documents.ProxyConfiguration

I try to test it by doing a test similar to this one : https://github.com/Azure/azure-documentdb-python/blob/07caab604adc7c8e3cadab918e8c599ab45f3b4b/test/crud_tests.py#L3734-L3743

But the proxy settings seems totally ignored
By checking the azure-documentdb-python code, it seems the proxy settings are used nowhere

Did I missed something ?

**Comment by srinathnarayanan** [comment]
Hi @sigma87 thanks for bringing this issue to our attention. This is a bug we are currently working on and we will have it in our next release.

**Comment by srinathnarayanan** [comment]
This has been fixed in versions >= 2.3.3
