### ISSUE TITLE
Missing support for direct connection mode (TCP and HTTPS)

### ISSUE THREAD

**Issue by evandropaula** [Azure/azure-cosmos-python#121]
Currently, pydocumentdb version 2.3.1 SDK does not support the direct connection mode for HTTPS nor TCP. Please add support.

[Metadata]
Metadata-Version: 2.0
Name: pydocumentdb
Version: 2.3.1
Summary: Azure DocumentDB Python SDK
Home-page: https://github.com/Azure/azure-documentdb-python
Author: Microsoft
Author-email: askdocdb@microsoft.com
License: MIT

[Impact]
Performance
SDK consistency across multiple platforms

[Repro Steps]
File: https://github.com/Azure/azure-documentdb-python/blob/d0929b4fdbf66780004c0744be74beeb7c90fa27/pydocumentdb/documents.py

class ConnectionMode(object):
    """Represents the connection mode to be used by the client.
    :ivar int Gateway:
        Use the Azure Cosmos DB gateway to route all requests. The
        gateway proxies requests to the right data partition.
    """
    Gateway = 0

**Comment by christopheranderson** [comment]
Thanks for the feature suggestion. We don't have any timeline to share, but we are investigating the best way of adding this support.

**Comment by clauney** [comment]
I know this issue is old, but is there any update? The current (I think) docs at https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.documents.connectionpolicy?view=azure-python indicate there's still no support for ConnectionMode = direct

**Comment by fabidick22** [comment]
Any update? :thinking:

**Comment by southpolesteve** [comment]
Unfortunately no ETA for direct mode in Python at this time. I wrote up some thoughts about direct mode in the JS SDK repo which describes some of what makes it challenging: https://github.com/Azure/azure-sdk-for-js/issues/4807#issuecomment-519307917

Closing this issue as active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python.
