### ISSUE TITLE
Timeout when attempting to create database

### ISSUE THREAD

**Issue by chcaru** [Azure/azure-cosmos-python#124]
When you have an account that has the maximum number of allowed databases, attempting to create a new one results in a timeout. There should be a clear error here.

``` python
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='account-id.documents.azure.com', port=443): Read timed out. (read timeout=60.0)
```

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
