### ISSUE TITLE
What is offerEnableRUPerMinuteThroughput when creating collections?

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cosmos-python#127]
When creating a collection, then `offerEnableRUPerMinuteThroughput` can be supplied in the options. I couldn't find any documentation on what this really means. In the Azure Portal one must select a "Throughput", there is no option to enable or disable anything.

**Comment by nuno-andre** [comment]
It was [a way of provisioning requests units when you run out your RUs](https://www.ascent.tech/wp-content/uploads/documents/microsoft/cosmos-db/cosmos-db.pdf) _(pp. 258-263)_ but [it was retired](https://stackoverflow.com/a/47303207/3775493).

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
