### ISSUE TITLE
Are collections created with "unlimited" storage capacity?

### ISSUE THREAD

**Issue by letmaik** [Azure/azure-cosmos-python#128]
The Azure Portal allows to create collections either with fixed size of 10GB without using partitions, or unlimited storage / partitioned:

![image](https://user-images.githubusercontent.com/530988/43201166-a2d578d0-900f-11e8-82ca-1e1cf3085a10.png)

I could not figure out how to influence this when using pydocumentdb when creating a collection. There also doesn't seem to be a way to specify the partition key path when doing so. I find this all quite confusing and would be happy if this is clarified in the docs and/or the library is changed to support everything the Azure Portal supports.

**Comment by sagarsharmas** [comment]
There is a pull request for Partition Key - https://github.com/Azure/azure-cosmos-python/pull/142.

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
