### ISSUE TITLE
0 rows returned by client lib, when server sends 429 on first page of query results

### ISSUE THREAD

**Issue by austindonnelly** [Azure/azure-cosmos-python#131]
There's a bug in how the client library deals with receiving "429 Too Many Requests" from the server when running a query.
If the server is so overloaded that it returns 429 starting right from the first page of query results, then the client mistakenly returns an empty result set to the caller.  I would have expected it to re-raise the 429 exception, so the caller knows it did not get the correct results.
This is bad because the caller cannot tell whether the query really did return 0 rows, or whether there was data but the server was too overloaded to return it.

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
