### ISSUE TITLE
documentation generates almost nothing

### ISSUE THREAD

**Issue by docgregt** [Azure/azure-cosmos-python#133]
I followed the directions to the letter and I get:
...
reading sources... [100%] index                                                or
WARNING: autodoc: failed to import module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'auth' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'base' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'consistent_hash_ring' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'constants' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'cosmos_client' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'default_retry_policy' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'documents' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'endpoint_discovery_retry_policy' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'errors' from module 'cosmos'; the following exception was raised:
No module named 'cosmos'
WARNING: autodoc: failed to import module 'execution_context' from module 'cosmos'; the following exception was raised:

etc.

**Comment by srinathnarayanan** [comment]
Hi @docgregt, Thanks for bringing this to our notice. We will be fixing this shortly when we release a patch update.

**Comment by srinathnarayanan** [comment]
this has been fixed in the 3.0.1 release
