### ISSUE TITLE
[('SSL routines', 'ssl3_write_pending', 'bad write retry')] with CreateItem on large dictionary

### ISSUE THREAD

**Issue by kevroy314** [Azure/azure-cosmos-python#135]
I'm writing several dictionaries using CreateItem and although most work, especially large ones throw [('SSL routines', 'ssl3_write_pending', 'bad write retry')] as an error. Googling around, many have mentioned this being a bug in requests prior to 2.9.0, but I'm way past that version, and I've run pip install -U on both requests and urllib3. Any suggestions? Is there a setting that will make it more robust to larger writes?

**Comment by moderakh** [comment]
@kevroy314 
questions:

1) which version of the SDK are you using?
2) which OS platform?
3) which version of Python

Also can you please provide repro code?

**Comment by kevroy314** [comment]
Sorry for the delayed response.

This is azure-cosmos 3.0.0, Python 3.6 via Anaconda3, and MacOSX 10.13.6.

I'm still working on reproducible code that doesn't involve private information. I'll post it if I can get it going. It's a little challenging because of the size of the data. I'm not convinced size is the only problem either because just throwing random data of a similar size at it didn't do it.

I'll post back when I can get a reproduction going or get more information. Thank you!

**Comment by privalof** [comment]
@moderakh  Happend to with azure-cosmos 3.0.0, and only if pyopenSSL installed. 
Created PR: https://github.com/Azure/azure-cosmos-python/pull/185

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
