### ISSUE TITLE
Connexion fails due to fr_FR locale on Ubuntu

### ISSUE THREAD

**Issue by vchalmel** [Azure/azure-cosmos-python#137]
I have two environments with python3 on Ubuntu and Windows using pydocumentdb to connect to cosmosdb.

Windows machine (python 3.5.4, locales set to fr_FR, CP_1252) can connect but Ubuntu machine (Python 3.5.2, locales set to fr_FR,UTF-8) couldn't. Error Message of the HTTPFailure is "The input date header is invalid format. Please pass in RFC 1123 style date format.
workaround by adding 
`
import locale

locale.setlocale(locale.LC_ALL,['en_US','UTF-8'])
`
(workaround found on a similar bug report for the java documentDB driver)

**Comment by christopheranderson** [comment]
Thanks for reporting and providing clear repro. Looks like we need to be more careful about which dates formats are getting used. We'll finish investigating and issue a fix.

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
