### ISSUE TITLE
Add support for Python 3.6 and 3.7

### ISSUE THREAD

**Issue by thedrow** [Azure/azure-cosmos-python#139]
Currently the README specifies that Python 3.3, 3.4 and 3.5 are supported.
In order to merge https://github.com/celery/celery/pull/4720 safely we need you guys to support 3.6 and 3.7. Our tests pass, but we'd rather have official support in case something goes wrong.
Are these Python versions supported? Is the README simply outdated?

**Comment by southpolesteve** [comment]
4.0 has been released and supports Python 3.x. If you run into any further issues you can open them in our new monorepo https://github.com/Azure/azure-sdk-for-python
