### ISSUE TITLE
Log retries

### ISSUE THREAD

**Issue by gugu91** [Azure/azure-cosmos-python#144]
Currently, there is no way of adding logs callbacks on reties as far as I can tell. Also, python logger seems to be initialised in a couple of classes but I can't find any calls. Is there something that can be done to surface why and when when client retries?

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
