### ISSUE TITLE
MaxDegreeOfParallelism concept missing in Python SDK

### ISSUE THREAD

**Issue by srinathnarayanan** [Azure/azure-cosmos-python#148]
The Python SDK currently does not honor MaxDegreeOfParallelism passed in the feedOptions like the .Net SDK does : https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.feedoptions.maxdegreeofparallelism?view=azure-dotnet#Microsoft_Azure_Documents_Client_FeedOptions_MaxDegreeOfParallelism

This is because of the reliance on the requests library and not using async io. Ask is to move from requests to async io and allow for MaxDegreeOfParallelism.

**Comment by bigdatamoore** [comment]
+1 on this

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
