### ISSUE TITLE
Publish tagged Github releases (was: No Official Releases?)

### ISSUE THREAD

**Issue by yehoshuadimarsky** [Azure/azure-cosmos-python#157]
Why are there no releases in GitHub, even though I see that there is in fact a version based release cadence - the latest stable release being 3.0.2 and latest beta is 3.0.3-SNAPSHOT. Am I missing something?

I am asking because I am the maintainer for this SDK on conda-forge and it would be nice to be able cleanly see what version is the latest for this library.

**Comment by srinathnarayanan** [comment]
We will be making official releases on Github starting V4.0.0, which is preview right now.

**Comment by christopheranderson** [comment]
For context, we're moving this repo into the azure python sdk mono repo by the end of the month, so it will be tracked from there.

**Comment by southpolesteve** [comment]
4.0 has been released. Active development will happen here https://github.com/Azure/azure-sdk-for-python
