### ISSUE TITLE
add wheel to PyPI for Python3

### ISSUE THREAD

**Issue by bigdatamoore** [Azure/azure-cosmos-python#158]
Can you please add a wheel to PyPI for Python3?  Currently I only see Python2 there and it is a pain because when using this with Azure Functions, it forces me to build from source which in turn requires Docker.   Anyways, it would be nice to have Python3 wheels available.   Thanks

**Comment by ealsur** [comment]
@srinathnarayanan What's our story with Python 3?

**Comment by bigdatamoore** [comment]
any update?  still waiting for this as it is making working with Python Azure Functions more difficult as it requires docker to build.  Having the binary wheel available in PyPI would make that easier and faster.

**Comment by srinathnarayanan** [comment]
Hi @bigdatamoore , I uploaded a python3 wheel for the latest version (3.0.2- https://pypi.org/project/azure-cosmos/#files ). Sorry for the delay!

**Comment by bigdatamoore** [comment]
Thanks so much.  You have no idea how much time this will save us in doing builds for Python azure functions.  I appreciate your quick response.
