### ISSUE TITLE
Query Partitioned Collection

### ISSUE THREAD

**Issue by MattHartz** [Azure/azure-cosmos-python#170]
Hi,

I'm still fairly new to cosmosdb, but from my understanding it appears that cosmos db enforces collection partitioning. I am trying to query my partitioned collection with

```results = list(client.QueryItems(collection_link, query, partition_key="id"))```

and I get the error

```{"code":"BadRequest","message":"Cross partition query is required but disabled. Please set x-ms-documentdb-query-enablecrosspartition to true, specify x-ms-documentdb-partitionkey, or revise your query to avoid this exception.\r\nActivityId: 748386a4-e6e1-4d31-a84c-2551df7779d9, Microsoft.Azure.Documents.Common/2.2.0.0"}```

Any ideas?

**Comment by jonahp-moran** [comment]
Same issue. Pretty disappointing to see that this month-old issue hasn't even been addressed. The docs for this API leave quite a bit to be desired.

For example - if anybody is actually going to see this - how does the `options` parameter work? I tried `{'x-ms-documentdb-query-enablecrosspartition': 'true'}`, `{'x-ms-documentdb-query-enablecrosspartition': True}`, nothing doing...

**Comment by Vin5** [comment]
This helped me:
```python
client.QueryItems(collection_link, query, { "enableCrossPartitionQuery": True })
```

**Comment by vchalmel** [comment]
The partition key for a specific query is simply meant to be enclosed in a dictionary (it's the query parameters dictionary) 

Here is a modified code from the original question
`results = list(client.QueryItems(collection_link, query, {partition_key:"id"}))`

Or you should provide a parameter to the query, or the client object, to allow cross-partition queries.

**Comment by srinathnarayanan** [comment]
@MattHartz you can perform a cross partition query using 

client.QueryItems(collection_link, query, { "enableCrossPartitionQuery": True })

or if you want to perform a query using a specific partitionKey, you can use

client.QueryItems(collection_link, query, { "partitionKey": "pk_value" })
