### ISSUE TITLE
How to send a query or stored procedure execution to a specific region/location ?

### ISSUE THREAD

**Issue by vchalmel** [Azure/azure-cosmos-python#176]
Once a connection is defined with several PreferredLocations defined in the connectionPolicy, is it possible to micro-manage query and storedprocedures posts to parallelize calls to each locations/regions ?

There is no examples including anything regions related, and as for now the doc is still empty well...

**Comment by southpolesteve** [comment]
This is not possible with a single client. You'll need a create a client for each region by setting preferred locations to a single value and then deciding which client to use in application code.
