### ISSUE TITLE
When can we expect 4.* release?

### ISSUE THREAD

**Issue by brandonmbanks** [Azure/azure-cosmos-python#188]
It looks like 4.0 is going to give us a lot of things that are needed. When can we expect that release? It looks like the last preview release was back on November 18th.

I see that work is being done to [migrate to the azure python sdk mono repo](https://github.com/Azure/azure-cosmos-python/issues/157#issuecomment-489826226). I can see the cosmos module in the [azure sdk for python](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/cosmos/azure-cosmos) Should I be looking elsewhere for code releases?

We are eagerly awaiting 4.0 and increased python support. Thank you all for the hard work.

**Comment by brandonmbanks** [comment]
Bump. @rnagpal @srinathnarayanan

**Comment by southpolesteve** [comment]
4.0 has been released from the monorepo! 😃 Future development will happen there.
