### ISSUE TITLE
Add __version__ to module

### ISSUE THREAD

**Issue by alfonsomhc** [Azure/azure-cosmos-python#20]
It is kind of standard to have a **version** variable that provides the module version. Please add that :)

http://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
