### ISSUE TITLE
Python SDK - Update Autoscale Throughput

### ISSUE THREAD

**Issue by Kanwrk** [Azure/azure-cosmos-python#208]
I am trying to update the Autoscale Throughput using Azure cosmos python SDK, not finding any methods or properties that can be used to update the Autoscale Throughput...

**Comment by southpolesteve** [comment]
@Kanwrk Can you file an issue in our new central repo? https://github.com/Azure/azure-sdk-for-python. We no longer maintain the Cosmos SDK in this repo.
