### ISSUE TITLE
ODM for DocumentDB?

### ISSUE THREAD

**Issue by rudimk** [Azure/azure-cosmos-python#46]
Having an object-document mapper for DocumentDB would be immensely helpful, instead of embedding raw queries within Python. Wondering if something along those lines is in the works? If not, maybe I could try building a basic ODM module.

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
