### ISSUE TITLE
ToArray()

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-cosmos-python#5]
is not exactly idiomatic Python. 

Saw the example here. http://azure.microsoft.com/en-us/documentation/articles/documentdb-python-application/ 

There should not be a need for such a method.

Also the naming convention does not meet Python. Please run this code through pep8.

**Comment by rnagpal** [comment]
Will take a look at pep8 convention and hopefully make the Python SDK complaint with it. Reopening this so that we can track this.

**Comment by ahmetalpbalkan** [comment]
@rnagpal great to hear, I hope it follows Python coding idioms completely; not just pep8.

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
