### ISSUE TITLE
CollectionManagement sample has an IDisposable that doesn't match it's docs

### ISSUE THREAD

**Issue by brettcannon** [Azure/azure-cosmos-python#81]
If you look at [IDisposable](https://github.com/Azure/azure-documentdb-python/blob/1766aa9fc7cfc3b61c71248866e543a293595f0d/samples/CollectionManagement/Program.py#L49) in the ManageCollections sample you will notice it says that it's for use in a context manager to call a `close()` method. But if you look at the actual code there's no call to a `close()` method. I also didn't find a `close()` method on the `DocumentClient` in the SDK docs for the single use of `IDisposable` in the code. Lastly, in Python's stdlib there is [`contextlib.closing()`](https://docs.python.org/3/library/contextlib.html#contextlib.closing) for this exact use-case.

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
