### ISSUE TITLE
Few questions (docs are hard to understand)

### ISSUE THREAD

**Issue by amitbend** [Azure/azure-cosmos-python#87]
Hi, I'm using `QueryDocuments` and the docs for pydocdb are very hard to understand, so i will ask here few questions:

1. where can i find the structure for a query dict (`query (dict) or (str), query`)
2. same for `options (dict), the request options for the request.`
3. How can i use `next()` on the results, let's say i want to fetch 10 results and later another 10. should i use in the query `top 10` or is it some kind of an option i'm missing?

thanks

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
