### ISSUE TITLE
Permissions Error on ReadMedia

### ISSUE THREAD

**Issue by elibol** [Azure/azure-cosmos-python#90]
Hi,

When I try reading a media upload, I get a permissions error. Here is a snippet of what I'm doing:

```
with open("large_text.txt") as fh:
    client.UpsertAttachmentAndUploadMedia(document['_self'], fh, {'contentType': 'application/text'})

attachment = [i for i in client.ReadAttachments(document['_self'])][0]
media = client.ReadMedia(attachment['media']) # this is where the error occurs
```

The Error:
```
{"code":"Unauthorized","message":"The input authorization token can\'t serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: ..."}
```

There isn't much documentation I could find on this, so any feedback is appreciated.

- Melih

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
