### ISSUE TITLE
import config?

### ISSUE THREAD

**Issue by Blutude** [Azure/azure-cosmos-python#94]
Hello,
What is the config module? Where can I download it? Can't I get the Host, Key and ID directly from the azure website?

**Comment by Blutude** [comment]
I am asking for /samples/DatabaseManagement/Program.py
I am trying to open my cosmosDB database on python.
Thanks,
Rony

**Comment by whSwitching** [comment]
got a same problem.  you can just remove "import config as cfg" and replace
`HOST = cfg.settings['host']`
`MASTER_KEY = cfg.settings['master_key']`
`DATABASE_ID = cfg.settings['database_id']`

with 

`HOST = "https://localhost:8081"`
`MASTER_KEY = "your key string"`
`DATABASE_ID = "your db id"`

**Comment by HussainMir** [comment]
We're maintaining these constants in a shared file "config.py" which is shared by all projects in the samples solution. Yes, alternatively you can define them in the same file i.e. program.py

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
