### ISSUE TITLE
Connection pool parameter is missing in connection policy

### ISSUE THREAD

**Issue by nikunj08** [Azure/azure-cosmos-python#99]

**Comment by khdang** [comment]
@nikunj08 can you please provide more details on this issue?

**Comment by prburgu** [comment]
I believe this is referring to the inability to configure connection pool used by requests session in cosmosdb_client. I see that cosmosdb client uses requests session, but it doesn't provide a way to customize the requests session, so we are stuck with the default connection pool the requests session provides.
https://github.com/Azure/azure-cosmos-python/blob/master/azure/cosmos/cosmos_client.py#L136

**Comment by southpolesteve** [comment]
Closing this issue due to age. Active development of our Python SDK has moved to https://github.com/Azure/azure-sdk-for-python. We have also released 4.0 which includes many updates and new features. If this issue still needs our attention, please reopen it in the new repository.
